### PR TITLE
Refactor suggestions

### PR DESCRIPTION
**Pull request by igorlg**
Hello!

Here are some refactoring suggestions, to facilitate the build and perhaps make a few things clearer:

- Moved apk binaries and scripts to folder dependencies/python/
- Packaged dependencies (above) as a [Lambda Layer](https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html)
- Added a Makefile to facilitate the build and deploy activities
- Added a `config.env.example` file to store variables (as opposed to passing them in the command line)
- Moved the test.json event file to the events/ folder, to match the AWS SAM model
- Added `requirements.txt` file with the Boto3 dependency of Lambda
- Moved the `apk-index` and `apk-sign` scripts to the Docker folder*

*: This is to make the Makefile dependency activity simpler to write, as then all apk files are pulled out of the same Docker container directory

### CODE REVIEW

**Comment by igorlg** [comment]
Hope this helps. Suggestions and/or complaints are always welcome!

**Review by lloydpick — APPROVED** [review]

**Comment by lloydpick** [comment]
Sorry, only just saw this so apologies on the delay. 

LGTM, we'd just need the commits to be signed to be merged.

**Comment by igorlg** [comment]
> Sorry, only just saw this so apologies on the delay.
> 
> LGTM, we'd just need the commits to be signed to be merged.

Commit amended with signature. Sorry for the force-push, but it felt simpler than raising a new PR.

**Comment by lloydpick** [comment]
👍  thanks for your contribution!

**Pull request merged**
